pipelines:
  branches:
    master:
      - step:
          name: Deploy to Registry
          services:
            - docker
          script:
            - export IMAGE_NAME=$DOCKER_HUB_USERNAME/sparx:$BITBUCKET_COMMIT
            - docker build -t $IMAGE_NAME .
            - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
            - docker push $IMAGE_NAME
      - step:
          name: Deploy to droplet
          script:
            - export IMAGE_NAME=$DOCKER_HUB_USERNAME/sparx:$BITBUCKET_COMMIT
            - pipe: atlassian/ssh-run:0.2.2
              variables:
                SSH_USER: $SSH_USER
                SERVER: $SSH_SERVER
                COMMAND: >
                  docker stop sparx-container || true;
                  docker rm sparx-container || true;
                  docker pull $IMAGE_NAME;
                  docker run -p $SERVER_PORT:$SERVER_PORT -d --name sparx-container $IMAGE_NAME
          services:
            - docker
