pipelines:
  branches:
    master:
      - step:
          name: Deploy to Registry
          script:
            - export IMAGE_NAME=your_name/project_name:$BITBUCKET_COMMIT
            - docker build -t $IMAGE_NAME .
            - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
            - docker push $IMAGE_NAME
      - step:
          name: Deploy to droplet
          script:
            - export IMAGE_NAME=your_name/project_name:$BITBUCKET_COMMIT
            - pipe: atlassian/ssh-run:0.2.2
              variables:
                SSH_USER: $SSH_USER
                SERVER: $SSH_SERVER
                COMMAND: >
                  docker stop $(docker ps -a -q --filter ancestor=$IMAGE_NAME)
                  docker rm $(docker ps -a -q --filter ancestor=$IMAGE_NAME)
                  docker run -p $SERVER_PORT:$SERVER_PORT -d $IMAGE_NAME
          services:
            - docker
