pipelines:
  branches:
    master:
      - step:
          name: Deploy to Registry
          services:
            - docker
          script:
            - export TAG=$BITBUCKET_COMMIT
            - export IMAGE_NAME=$DOCKER_HUB_USERNAME/sparx:$TAG
            - docker build -t $IMAGE_NAME .
            - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
            - docker push $IMAGE_NAME

      - step:
          name: Transfer Files to Droplet
          script:
            - pipe: atlassian/scp-deploy:0.3.11
              variables:
                USER: $SSH_USER
                SERVER: $SSH_SERVER
                REMOTE_PATH: '/var/www/sparx-api/'
                LOCAL_PATH: '.env docker-compose.yml .env.prod'

      - step:
          name: Update .env on server
          script:
            - pipe: atlassian/ssh-run:0.2.2
              variables:
                SSH_USER: $SSH_USER
                SERVER: $SSH_SERVER
                COMMAND: |
                  sh -c '
                  update_or_append() {
                    local file=$1
                    local key=$2
                    local value=$3

                    if grep -qE "^$key=" "$file"; then
                      sed -i "s/^$key=.*/$key=$value/" "$file"
                    else
                      echo "$key=$value" >> "$file"
                    fi
                  }

                  update_or_append "/var/www/sparx-api/.env" "DOCKER_HUB_USERNAME" "$DOCKER_HUB_USERNAME"
                  update_or_append "/var/www/sparx-api/.env" "TAG" "$BITBUCKET_COMMIT"
                  '

      - step:
          name: Deploy to droplet
          script:
            - pipe: atlassian/ssh-run:0.2.2
              variables:
                SSH_USER: $SSH_USER
                SERVER: $SSH_SERVER
                COMMAND: |
                  sh -c '
                  cd /var/www/sparx-api/ && \
                  (docker-compose down || true) && \
                  docker-compose pull && \
                  docker-compose up -d && \
                  docker image prune -f
                  '
