version: '3.9'

services:
  app:
    container_name: api
    env_file:
      - .env
    image: $DOCKER_HUB_USERNAME/navinotes:$TAG
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    environment:
      DB_TYPE: postgres
      PG_USER: ${POSTGRES_USER}
      PG_PASSWORD: ${POSTGRES_PASSWORD}
      PG_DB: ${POSTGRES_DB}
      PG_PORT: ${POSTGRES_PORT}
      PG_HOST: db
      NODE_ENV: development
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
      - /var/log:/var/log
      - /etc/letsencrypt:/etc/letsencrypt

  db:
    container_name: postgres
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      GUNICORN_ACCESS_LOGFILE: /dev/null
    ports:
      - '5050:80'
    depends_on:
      - db

volumes:
  pgdata:
