version: '3.9'

networks:
  sparx-network:
    driver: bridge

services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    ports:
      - '5432:5432'
    networks:
      - sparx-network
    deploy:
      resources:
        limits:
          cpus: '0.25' # Limit to 50% of a single CPU core
          memory: '512M' # Limit to 512MB of memory
        reservations:
          cpus: '0.25' # Reserve 25% of a single CPU core
          memory: '256M' # Reserve 256MB of memory
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      GUNICORN_ACCESS_LOGFILE: /dev/null
    ports:
      - '5050:80'
    depends_on:
      - db

volumes:
  pgdata:
