version: '3.9'

networks:
  sparx-network:
    driver: bridge

services:
  app:
    env_file:
      - .env
    image: $DOCKER_HUB_USERNAME/sparx:$TAG
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    ports:
      - '3000:3000'
    networks:
      - sparx-network
    volumes:
      - /var/log:/var/log
      - /etc/letsencrypt:/etc/letsencrypt
