export enum MessageType {
  NewUser = 'NEW_USER',
  UpdateUser = 'UPDATE_USER',
  RemoveUser = 'REMOVE_USER',
  JoinChannel = 'JOIN_CHANNEL',
  LeaveChannel = 'LEAVE_CHANNEL',
  UpdateSection = 'UPDATE_SECTION',
  RemoveSection = 'REMOVE_SECTION',
  AddChannelToSection = 'ADD_CHANNEL_TO_SECTION',
  ReorderSections = 'REORDER_SECTIONS',
  UpdateMessage = 'UPDATE_MESSAGE',
  RemoveMessage = 'REMOVE_MESSAGE',
  AddUserStatus = 'ADD_USER_STATUS',
  UpdateUserStatus = 'UPDATE_USER_STATUS',
  RemoveUserStatus = 'REMOVE_USER_STATUS',
}
