name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and push Docker image
        run: |
          export TAG=${{ github.sha }}
          export IMAGE_NAME=${{ secrets.DOCKER_HUB_USERNAME }}/navinotes:$TAG
          docker build --no-cache --build-arg NODE_ENV=production -t $IMAGE_NAME .
          docker push $IMAGE_NAME
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/navinotes/ && \
            echo "DOCKER_HUB_USERNAME=${{ secrets.DOCKER_HUB_USERNAME }}" >> .env && \
            echo "TAG=${{ github.sha }}" >> .env && \
            (docker-compose -f docker-compose.db.yml up -d || true) && \
            scp docker-compose.db.yml docker-compose.prod.yml ${{ secrets.SSH_USER }}@${{ secrets.SSH_SERVER }}:/var/www/navinotes/ && \
            (docker-compose -f docker-compose.prod.yml down || true) && \
            docker-compose -f docker-compose.prod.yml pull && \
            docker-compose -f docker-compose.prod.yml up -d && \
            docker image prune -f
