name: Test SSH Connection

on: [push]

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Test SSH
        run: ssh -vvv -i ${{ secrets.SSH_KEY }} -o StrictHostKeyChecking=accept-new root@165.227.44.99 'echo "SSH connection successful"'
